
language: node_js
node_js:
- "node"

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email:
    on_success: change
    on_failure: always

stages:
- test
- build
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: test
    script:
    - yarn test-ci

  - stage: deploy
    script: yarn deploy

    after_script:
    - yarn alias
    - yarn clear-deployments
